sonar.projectKey=Enigma7777777_gestion
sonar.organization=Enigma7777777
sonar.projectName=gestion
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.language=java
sonar.java.binaries=target/classes
sonar.sources=src/main/java
sonar.tests=src/test/java
